src/Jumph/Bundle/DashboardBundle/Entity/ActivityStream.php
<?php

/**
 * This file is part of the Jumph package.
 *
 * (c) Peter Nijssen
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Jumph\Bundle\DashboardBundle\Entity;

use Jumph\Bundle\UserBundle\Entity\User;

class ActivityStream
{

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $objectId;

    /**
     * @var string
     */
    private $objectType;

    /**
     * @var string
     */
    private $verb;

    /**
     * @var \DateTime
     */
    private $createdAt;

    /**
     * @var User
     */
    private $user;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set objectId
     *
     * @param string $objectId
     *
     * @return ActivityStream
     */
    public function setObjectId($objectId)
    {
        $this->objectId = $objectId;

        return $this;
    }

    /**
     * Get objectId
     *
     * @return string 
     */
    public function getObjectId()
    {
        return $this->objectId;
    }

    /**
     * Set objectType
     *
     * @param string $objectType
     *
     * @return ActivityStream
     */
    public function setObjectType($objectType)
    {
        $this->objectType = $objectType;

        return $this;
    }

    /**
     * Get objectType
     *
     * @return string 
     */
    public function getObjectType()
    {
        return $this->objectType;
    }

    /**
     * Set verb
     *
     * @param string $verb
     *
     * @return ActivityStream
     */
    public function setVerb($verb)
    {
        $this->verb = $verb;

        return $this;
    }

    /**
     * Get verb
     *
     * @return string 
     */
    public function getVerb()
    {
        return $this->verb;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     *
     * @return ActivityStream
     */
    public function setCreatedAt(\DateTime $createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set user
     *
     * @param User $user
     *
     * @return ActivityStream
     */
    public function setUser(User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return User
     */
    public function getUser()
    {
        return $this->user;
    }
}

src/Jumph/Bundle/DashboardBundle/Entity/DashboardBlockInterface.php
<?php

/**
 * This file is part of the Jumph package.
 *
 * (c) Peter Nijssen
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Jumph\Bundle\DashboardBundle\Entity;

interface DashboardBlockInterface
{
    /**
     * @return string
     */
    public function getColor();

    /**
     * @return string
     */
    public function getIcon();

    /**
     * @return string
     */
    public function getItemName();

    /**
     * @return string
     */
    public function getLink();

    /**
     * @return int
     */
    public function getTotalItems();
}

src/Jumph/Bundle/DashboardBundle/Controller/DashboardController.php
<?php

/**
 * This file is part of the Jumph package.
 *
 * (c) Peter Nijssen
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Jumph\Bundle\DashboardBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;

class DashboardController extends Controller
{

    /**
     * Dashboard overview page
     *
     * @return Response A Response instance
     */
    public function overviewAction()
    {
        $blocksContainer = $this->get('jumph_dashboard.dashboard_block_container');

        return $this->render("JumphDashboardBundle:Dashboard:overview.html.twig", array(
            'blocks' => $blocksContainer->getAllBlocks()
        ));
    }
}

src/Jumph/Bundle/DashboardBundle/Tests/Controller/CalendarControllerTest.php
<?php

/**
 * This file is part of the Jumph package.
 *
 * (c) Peter Nijssen
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Jumph\Bundle\DashboardBundle\Tests\Controller;

use Jumph\Bundle\AppBundle\Tests\BaseWebTestCase;

/**
 * Functional dashboard controller tests
 */
class DashboardControllerTest extends BaseWebTestCase
{
    /**
     * Test the overview method
     */
    public function testOverview()
    {
        $this->client->request('GET', '/');
        $this->assertTrue($this->client->getResponse()->isSuccessful());
    }
}

src/Jumph/Bundle/DashboardBundle/Resources/views/Dashboard/overview.html.twig
{% extends '::base.html.twig' %}

{% block title %}
    {{ parent() }} | Dashboard
{% endblock %}

{% block headerContent %}
    <h1>
        Dashboard
        <small>Overview</small>
    </h1>
    <ol class="breadcrumb">
        <li><i class="fa fa-dashboard"></i> Dashboard</li>
    </ol>
{% endblock %}

{% block content %}
    <div class="row">
        {% for block in blocks %}
            <div class="col-lg-3 col-xs-6">
                <div class="small-box bg-{{ block.color }}">
                    <div class="inner">
                        <h3>
                            {{ block.totalItems }}
                        </h3>
                        <p>
                            {{ block.itemName }}
                        </p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-{{ block.icon }}"></i>
                    </div>
                    <a href="{{ block.link }}" class="small-box-footer">
                        More info <i class="fa fa-arrow-circle-right"></i>
                    </a>
                </div>
            </div>
        {% endfor %}

        <div class="col-lg-12 col-xs-12">
            <ul class="timeline">
                <li class="time-label">
                    <span class="bg-red">
                        18 March. 2014
                    </span>
                </li>
                <li>
                    <i class="fa fa-envelope bg-blue"></i>
                    <div class="timeline-item">
                        <span class="time"><i class="fa fa-clock-o"></i> 12:05</span>
                        <h3 class="timeline-header"><a href="#">Support Team</a> sent you and email</h3>
                        <div class="timeline-body">
                            Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles,
                            weebly ning heekya handango imeem plugg dopplr jibjab, movity
                            jajah plickers sifteo edmodo ifttt zimbra. Babblely odeo kaboodle
                            quora plaxo ideeli hulu weebly balihoo...
                        </div>
                        <div class='timeline-footer'>
                            <a class="btn btn-primary btn-xs">Read more</a>
                            <a class="btn btn-danger btn-xs">Delete</a>
                        </div>
                    </div>
                </li>
                <li>
                    <i class="fa fa-building bg-aqua"></i>
                    <div class="timeline-item">
                        <span class="time"><i class="fa fa-clock-o"></i> 5 mins ago</span>
                        <h3 class="timeline-header no-border"><a href="#">Peter Nijssen</a> added client "Peter Nijssen"</h3>
                    </div>
                </li>
                <li>
                    <i class="fa fa-comments bg-yellow"></i>
                    <div class="timeline-item">
                        <span class="time"><i class="fa fa-clock-o"></i> 27 mins ago</span>
                        <h3 class="timeline-header"><a href="#">Jay White</a> commented on your post</h3>
                        <div class="timeline-body">
                            Take me to your leader!
                            Switzerland is small and neutral!
                            We are more like Germany, ambitious and misunderstood!
                        </div>
                        <div class='timeline-footer'>
                            <a class="btn btn-warning btn-flat btn-xs">View comment</a>
                        </div>
                    </div>
                </li>
                <li class="time-label">
                                    <span class="bg-green">
                                        3 Jan. 2014
                                    </span>
                </li>
                <li>
                    <i class="fa fa-clock-o"></i>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}